openapi: 3.0.0
info:
  version: '1.0'
  title: REST API
  contact:
    name: Ivan
    email: i.am.ivan.ilinov@gmail.com
servers:
  - url: 'https://example.com/v1.0'
    description: Live Server
tags:
  - name: API for Educational System
    description: |
      Basic operations with entity: User, Students, Subjects.
security:
  - SecretApiKey: []
  - JWT: []
paths:
#1.Регистрация
  /register:
    $ref: ./paths/createuser.yaml
#2.Авторизация
  /auth:
    $ref: ./paths/auth.yaml
#3.Студент (CRUD+ReadAll)
  /createStudent:
    $ref: ./paths/student/createStudent.yaml
  /updateStudent{id}:
    $ref: ./paths/student/updateStudent.yaml
  /deleteStudent{id}:
    $ref: ./paths/student/deleteStudent.yaml
  /getStudent{id}:
    $ref: ./paths/student/getStudent.yaml
  /getStudents:
    $ref: ./paths/student/getStudents.yaml
#4.Предмет (CRUD+ReadAll)
  /createSubject:
    $ref: ./paths/subject/createSubject.yaml
  /updateSubject{id}:
    $ref: ./paths/subject/updateSubject.yaml
  /deleteSubject{id}:
    $ref: ./paths/subject/deleteSubject.yaml
  /getSubject{id}:
    $ref: ./paths/subject/getSubject.yaml
  /getSubjects:
    $ref: ./paths/subject/getSubjects.yaml  

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT