openapi: 3.0.0
info:
  version: '1.0'
  title: REST API
  contact:
    name: Ivan
    email: i.am.ivan.ilinov@gmail.com
servers:
  - url: 'https://example.com/v1.0'
    description: Live Server
tags:
  - name: API for Educational System
    description: |
      Basic operations with entity: User, Students, Subjects.
security:
  - SecretApiKey: []
  - JWT: []
paths:
#1.Регистрация
  /createuser:
    $ref: ./paths/createuser.yaml
#2.Авторизация
  /auth:
    $ref: ./paths/auth.yaml
#3.Студент (CRUD+ReadAll)
  /students:
    $ref: ./paths/students.yaml
  /student/{studentId}:
    $ref: ./paths/student@{studentId}.yaml
#4.Предмет (CRUD+ReadAll)
  /subjects:
    $ref: ./paths/subjects.yaml
  /subject/{subjectId}:
    $ref: ./paths/subject@{subjectId}.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT